### ISSUE TITLE
task: Various fixes for infrahub sync

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4046]
### Component

Not Sure

### Task Description

Following test here is a few improvements to bring to infrahubsync:

- [x] Missing dependency tqdm

- [x] Unclear error message when pointing to a file that doesn't exist

- [x] Miss leading error message says config_file

- [x] Trailing warning message
```console
python3.9/site-packages/pydantic/_internal/_fields.py:161: UserWarning: Field "model_flags" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
```

- [x] Wrong diffsync generated when attribute is unique on Infrahub side

- [x] Typo in message displayed when there is no diff
```console
No diffence found. Nothing to sync
```

**Comment by BaptisteGi** [comment]
> * [ ]  Trailing warning message
Moved to opsmill/infrahub-sync#2
