### ISSUE TITLE
task: Improvements for infrahub sync documentation

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#4047]
### Component

Documentation & Examples

### Task Description

- [ ] Mention that SDK might be required depending the system used
`ModuleNotFoundError: No module named 'pynetbox'`

- [ ] Detail a bit more usage for command "name" "config file" and "directory"

- [ ] Not fully clear what goes where in the mapping for yaml (source vs destination ...)
