### ISSUE TITLE
feature: Results Pagination in GraphQL and in the Frontend 

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#409]
### Component

Frontend UI, API Server / GraphQL, Python SDK

### Describe the Feature Request

In order to support bigger dataset we need to implement the support for results pagination, first in GraphQL then in the Frontend and the Python SDK

Most likely the support for pagination will require to significantly change the structure of the GraphQL Schema. There are multiple possible solutions available that have been documented [here](https://graphql.org/learn/pagination/).

Here is an example of what a query could look like with and without pagination

<table>
<tr>
<th>Current</th>
<th>With Pagination</th>
</tr>
<tr>
<td>

```graphql
{
  location {
    id
    tags {
      id
      name {
        value
      }
    }
  }
}
```
</td>
<td>

```graphql
{
  location {
    id
    tags {
      totalCount
      edges {
        node {
          id
          name {
            value
          }
        }
        cursor
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}

```

</td>
</tr>
</table>

Before making a decision we need to investigate what would be easier to implement in the frontend based on the capability (or not) of the existing client and what we can do in the backend.

> There are multiple options available to query the result, with flags like `first`, `offset`, `after` or `cursor`, not sure if we'll be able to support all of them from the start

TODO:
- [x] Create issue to track implementation in the Backend
- [x] Create issue to track implementation in the Frontend
- [x] Create issue to track implementation in the Python SDK
