### ISSUE TITLE
task: streamline release note creation

### ISSUE THREAD

**Issue by lykinsbd** [opsmill/infrahub#4519]
### Component

Documentation & Examples

### Task Description

As part of the ongoing evolution of Infrahub's release process, Towncrier is generating the CHANGELOG.md file. However, many manual steps remain to process that information and generate the required output for the documentation website and the GitHub release notes.

As a maintainer of Infrahub, I would like to be able to call on a single Invoke task to:

- [ ] Bump the project version (ala, `poetry version <patch/minor/major>`)
- [ ] Install the new project version in the dev environment (to allow Towncrier to see the correct version for release)
- [ ] Read and validate the Towncrier "Newsfragment" files with both `towncrier build --draft`/`towncrier check` and `invoke docs.lint` (MDlint and Vale)
- [ ] Copy the textual output from `towncrier build --draft` and place it into:
  - [ ] A release note file in the documentation (creating one for this release if it does not already exist)
  - [ ] A draft GitHub release (creating one for this release if it does not already exist)
- [ ] Generate CHANGELOG.md updates and cleanup Newsfragments with `towncrier build`
