### ISSUE TITLE
task: Fix all redirects

### ISSUE THREAD

**Issue by pa-lem** [opsmill/infrahub#802]
### Component

Frontend UI

### Task Description

If there is anything that is not working as expected, we should redirect:
- [ ] if the user is authenticated but the backend doesn't return a result for the access token
  - we should logout the user
- [x] if the object name is not found in the schema (for example `/objects/nothing`)
  - [ ] same think with all menu, like `/group` and `/branches`
  - we should redirect to `/`
- [ ] if the object id is not found (for example `/objects/Device/nothing`)
  - we should display a relevant message as the object is not found
- [ ] if a menu item doesn't exist (for example `/nothing`)
  - we should redirect to `/`
